### PR TITLE
Fix triangle picker clamping, timeline seek scroll offset, and layer color UI sync

### LINKED ISSUE #27: [BUG] Triangle color picker bounds not respected
## Bug Description
When using the triangle color picker, the cursor can be scrolled past the end of the triangle's bounds, along the path of an arbitrary side.

## Steps to Reproduce
1. Enable triangle picker.
2. Click within the triangle region.
3. Move the mouse cursor outside of the triangle, through one of its corners.

## Expected Behavior
The picker should remain fixed at the triangle corner.

## Actual Behavior
The picker appears to scroll past the triangle's bounds.

## Screenshots
Image

### PR DESCRIPTION
**Pull request by immalloy**
## Description

This PR includes two commits that address multiple UI issues and menu/app-shell improvements.

* **Commit `240642f...`** fixes three targeted bugs:

  * Triangle SV picker handle could escape triangle bounds when dragging through corners (now strictly clamped).
  * Timeline click-to-seek misaligned when horizontally scrolled (scroll offset was applied incorrectly).
  * Switching layers didn’t update the visible color wheel / swatch UI consistently (now synced across all layer-change paths).

* **Commit `089c5d7...`** updates menus and app shell wiring/styling:

  * Menu/topbar wiring and control styling updates.
  * Modal/home-flow related markup and CSS changes.
  * Touch points across editor/render paths related to layout and menu handling.

**Important:** The **canvas-aspect sizing mismatch** is still present and is **not** claimed as fixed by this PR.

Fixes #27 #26 #23 

## Type of Change

* [x] Bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] Documentation update
* [x] Code refactoring
* [x] Performance improvement
* [x] Other (please describe): Menu/app shell UI + styling updates

## Changes Made

* Triangle color picker SV clamping now uses strict geometric clamping to keep the handle inside triangle bounds (including corners).
* Timeline click-to-seek now maps click position correctly under horizontal scroll (no drift when `scrollX > 0`).
* Layer switching now synchronizes color UI (color wheel + swatches/FG UI) consistently across:

  * normal layer changes
  * swatch-driven activation
  * undo/redo history jumps
  * cross-layer swatch moves
* Updated menu wiring + UI shell components and related CSS to support improved menus/modals behavior.
* Improved keyboard handling / wiring for menus.

## Testing

Please describe the tests that you ran to verify your changes:

* [X] Tested in Chrome
* [ ] Tested in Firefox
* [ ] Tested in Safari
* [ ] Tested in Edge
* [ ] Tested on mobile devices (if applicable)

**Test Configuration:**

* OS: Zorin OS/Debian
* Browser: Ungoogled Chromium

## Screenshots (if applicable)

image
image

## Checklist

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [X] I have tested my changes thoroughly
* [ ] Any dependent changes have been merged and published

## Related Issues

#27 #26 #23 

## Additional Notes

* Canvas-aspect sizing mismatch remains unresolved; recommend a follow-up PR focused solely on unifying aspect frame sizing with the actual canvas sizing path and/or refactoring to a frame-vs-workspace model.

### CODE REVIEW

File: celstomp/js/ui/color-wheel.js [hunk 1]
```diff
@@ -70,25 +184,27 @@ function updateFromSVPoint(x, y) {
...
-        else if (cl3 < 0) { cl3 = 0; cl1 = cl1 / (cl1 + cl2); cl2 = 1 - cl1; }
-
-        hsvPick.v = cl1 + cl2;
-        hsvPick.s = hsvPick.v > 0.0001 ? (cl1 / hsvPick.v) : 0;
+        const tri = getSVTriangleGeom(g);
+        const baryRaw = barycentricSV(dx, dy, tri);
+        let px = dx;
+        let py = dy;
+        if (baryRaw.l1 < 0 || baryRaw.l2 < 0 || baryRaw.l3 < 0) {
+            const clamped = closestPointOnSVTriangle(dx, dy, tri);
```
Comment (hingler) [inline celstomp/js/ui/color-wheel.js]: ty for putting the work into this ux fix

File: celstomp/celstomp-app.js [hunk 2]
```diff
@@ -89,10 +89,23 @@
         const autofillToggle = $("autofillToggle");
         const fillCurrentBtn = $("fillCurrent");
         const fillAllBtn = $("fillAll");
+        const clearCelBtn = $("clearCelBtn");
```
Comment (hingler) [inline celstomp/celstomp-app.js]: keep these declarations scoped to their relevant functions, instead of further polluting the namespace. not a dealbreaker for me bc its in line with the precedent we've set but in the future avoid placing more decls up here unless absolutely necessary (even if it means fetching the same element in every function call)

**Comment by hingler** [comment]
also, just to confirm: the aspect ratio changes solely concern menus?

**Review by hingler — CHANGES_REQUESTED** [review]
remove last commit

**Review by hingler — APPROVED** [review]
